"""
VCP Status Update PDF Generator.

Audience: portco management team.
Content: milestone scorecard only — what's on track, what isn't.
No IRR data, no sector benchmarks, no narrative beyond priority action.
3 pages: Cover · Milestone Scorecard · Priority Actions + Confidence
"""
from __future__ import annotations

import io
from datetime import date
from typing import Any, Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white
from reportlab.pdfgen import canvas as rl_canvas

W, H = A4

NAVY       = HexColor("#1E3A8A")
BODY_TEXT  = HexColor("#1E293B")
MUTED      = HexColor("#64748B")
BORDER     = HexColor("#CBD5E1")
STATUS_R   = HexColor("#DC2626")
STATUS_A   = HexColor("#D97706")
STATUS_G   = HexColor("#059669")

ML, MR, MT, MB = 45, 45, 45, 45
CW = W - ML - MR


def _status_color(status: str):
    s = (status or "").strip()
    if s in ("Red", "Behind"):
        return STATUS_R
    if s in ("Amber", "At Risk"):
        return STATUS_A
    if s in ("Green", "On Track", "Complete"):
        return STATUS_G
    return MUTED


def _fmt(v: Any, metric: str = "") -> str:
    if v is None:
        return "—"
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    m = (metric or "").lower()
    if "margin" in m or "growth" in m:
        return f"{f:.1%}"
    if "debt" in m or "leverage" in m:
        return f"{f:.2f}x"
    if abs(f) >= 1e6:
        return f"£{f / 1e6:.1f}M"
    if abs(f) >= 1e3:
        return f"£{f / 1e3:.0f}k"
    if abs(f) < 1:
        return f"{f:.1%}"
    return str(round(f, 2))


def _footer(c, page_num: int, report_date: str):
    c.setFillColor(NAVY)
    c.rect(0, 0, W, 28, fill=1, stroke=0)
    c.setFillColor(HexColor("#8ba3be"))
    c.setFont("Helvetica", 7)
    c.drawString(ML, 9, f"VCP Status Update · {report_date}")
    c.drawRightString(W - MR, 9, f"Page {page_num}  ·  CONFIDENTIAL")


def generate_vcp_status_pdf(
    company_name: str,
    period: str,
    milestones: List[Dict[str, Any]],
    drift_results: List[Dict[str, Any]],
    priority_action: str = "",
    confidence_statement: str = "",
    report_date: Optional[str] = None,
) -> bytes:
    if report_date is None:
        report_date = date.today().strftime("%-d %B %Y")

    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)

    # -------------------------------------------------------------------
    # Page 1: Cover
    # -------------------------------------------------------------------
    # White page, thin navy header band, clean text
    c.setFillColor(NAVY)
    c.rect(0, H - 6, W, 6, fill=1, stroke=0)

    c.setFillColor(BODY_TEXT)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(ML, H - 100, company_name)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(ML, H - 128, "VCP Status Update")

    c.setFont("Helvetica", 12)
    c.setFillColor(MUTED)
    c.drawString(ML, H - 148, period)

    c.setStrokeColor(BORDER)
    c.setLineWidth(0.5)
    c.line(ML, H - 170, ML + 180, H - 170)

    c.setFillColor(BODY_TEXT)
    c.setFont("Helvetica", 9)
    c.drawString(ML, H - 192, f"Prepared by: Operating Partner Team")
    c.drawString(ML, H - 208, f"Date: {report_date}")
    c.drawString(ML, H - 224, "Classification: Confidential")

    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7)
    c.drawString(ML, H - 260, "Generated by PE Value Creation Copilot")

    # Status summary
    green = sum(1 for r in drift_results if r.get("status") == "Green")
    red   = sum(1 for r in drift_results if r.get("status") == "Red")
    amber = sum(1 for r in drift_results if r.get("status") == "Amber")
    total = len(drift_results)

    y_card = H - 330
    card_w = (CW - 16) / 3
    for i, (val, lbl, col) in enumerate([
        (str(green), "On Track",  STATUS_G),
        (str(amber), "At Risk",   STATUS_A),
        (str(red),   "Behind",    STATUS_R),
    ]):
        cx = ML + i * (card_w + 8)
        c.setStrokeColor(BORDER)
        c.setFillColor(white)
        c.setLineWidth(1)
        c.roundRect(cx, y_card, card_w, 70, 4, fill=1, stroke=1)
        c.setFillColor(col)
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(cx + card_w / 2, y_card + 38, val)
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 8)
        c.drawCentredString(cx + card_w / 2, y_card + 22, lbl)

    _footer(c, 1, report_date)
    c.showPage()

    # -------------------------------------------------------------------
    # Page 2: Milestone Scorecard
    # -------------------------------------------------------------------
    c.setFillColor(NAVY)
    c.rect(ML, H - MT - 32, CW, 32, fill=1, stroke=0)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(ML + 10, H - MT - 20, "VCP MILESTONE SCORECARD")
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#8ba3be"))
    c.drawRightString(ML + CW - 10, H - MT - 20, f"As of {period}")

    # Summary strip
    y = H - MT - 32 - 10
    strip_h = 32
    c.setFillColor(HexColor("#f1f5f9"))
    c.roundRect(ML, y - strip_h, CW, strip_h, 3, fill=1, stroke=0)
    for i, (val, lbl, col) in enumerate([
        (str(green), "On Track", STATUS_G),
        (str(amber), "At Risk",  STATUS_A),
        (str(red),   "Behind",   STATUS_R),
        (str(total - green - amber - red), "No Data", MUTED),
    ]):
        cx = ML + i * (CW / 4) + CW / 8
        c.setFillColor(col)
        c.setFont("Helvetica-Bold", 14)
        c.drawCentredString(cx, y - 14, val)
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 7)
        c.drawCentredString(cx, y - 26, lbl)
    y -= strip_h + 12

    # Build row data: merge milestones with drift results
    drift_by_init = {r.get("initiative", ""): r for r in drift_results}
    rows = {}
    for m in milestones:
        k = m.get("initiative", "")
        rows[k] = {"m": m, "d": drift_by_init.get(k, {})}
    for r in drift_results:
        k = r.get("initiative", "")
        if k not in rows:
            rows[k] = {"m": {}, "d": r}

    # Column headers
    cols = [
        ("INITIATIVE",  180, "L"),
        ("CATEGORY",     70, "L"),
        ("TARGET",       70, "R"),
        ("ACTUAL",       70, "R"),
        ("GAP",          50, "R"),
        ("DUE",          50, "R"),
        ("STATUS",       15, "C"),
    ]
    hh = 20
    c.setFillColor(HexColor("#1e293b"))
    c.rect(ML, y - hh, CW, hh, fill=1, stroke=0)
    xp = ML + 6
    for lbl, cw, align in cols:
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 7)
        if align == "R":
            c.drawRightString(xp + cw - 4, y - 13, lbl)
        elif align == "C":
            c.drawCentredString(xp + cw / 2, y - 13, lbl)
        else:
            c.drawString(xp + 4, y - 13, lbl)
        xp += cw
    y -= hh

    ROW_ALT = HexColor("#f8fafc")
    for ri, (key, row) in enumerate(rows.items()):
        m, d = row["m"], row["d"]
        status = d.get("status", "Not Evaluable")
        col = _status_color(status)

        rh = 26
        c.setFillColor(white if ri % 2 == 0 else ROW_ALT)
        c.rect(ML, y - rh, CW, rh, fill=1, stroke=0)
        c.setFillColor(col)
        c.rect(ML, y - rh, 4, rh, fill=1, stroke=0)

        metric = m.get("metric", d.get("metric", ""))
        vals = [
            m.get("initiative", d.get("initiative", "—")),
            m.get("category", d.get("category", "—")).title(),
            _fmt(d.get("target_value"), metric),
            _fmt(d.get("actual_value"), metric),
            f"{d.get('gap_pct'):+.1%}" if d.get("gap_pct") is not None else "—",
            str(m.get("target_date", d.get("target_date", "—")) or "—")[:10],
            "",
        ]

        xp = ML + 6
        for vi, ((_, cw, align), val) in enumerate(zip(cols, vals)):
            if vi == 6:
                c.setFillColor(col)
                c.circle(xp + cw / 2, y - rh / 2, 5, fill=1, stroke=0)
                xp += cw
                continue
            c.setFillColor(BODY_TEXT if vi not in (3, 4) else col)
            c.setFont("Helvetica-Bold" if vi in (0, 3) else "Helvetica", 8)
            display = val
            if vi == 0 and c.stringWidth(display, "Helvetica-Bold", 8) > cw - 14:
                while c.stringWidth(display + "...", "Helvetica-Bold", 8) > cw - 14 and len(display) > 8:
                    display = display[:-1]
                display = display + "..."
            if align == "R":
                c.drawRightString(xp + cw - 4, y - rh / 2 - 3, display)
            elif align == "C":
                c.drawCentredString(xp + cw / 2, y - rh / 2 - 3, display)
            else:
                c.drawString(xp + 6, y - rh / 2 - 3, display)
            xp += cw

        c.setStrokeColor(BORDER)
        c.setLineWidth(0.3)
        c.line(ML, y - rh, ML + CW, y - rh)
        y -= rh

    y -= 10
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7)
    c.drawString(ML, y, "Red = >10% below target · Amber = 5–10% · Green = within ±5%")

    _footer(c, 2, report_date)
    c.showPage()

    # -------------------------------------------------------------------
    # Page 3: Priority Action + Confidence
    # -------------------------------------------------------------------
    c.setFillColor(NAVY)
    c.rect(ML, H - MT - 32, CW, 32, fill=1, stroke=0)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(ML + 10, H - MT - 20, "PRIORITY ACTIONS & NOTES")

    y = H - MT - 32 - 20

    if priority_action:
        pa_h = 60
        c.setFillColor(HexColor("#fffbeb"))
        c.setStrokeColor(HexColor("#f6ad55"))
        c.setLineWidth(1.5)
        c.roundRect(ML, y - pa_h, CW, pa_h, 5, fill=1, stroke=1)
        c.setFillColor(HexColor("#c05621"))
        c.rect(ML, y - pa_h, 5, pa_h, fill=1, stroke=0)
        c.setFillColor(HexColor("#c05621"))
        c.setFont("Helvetica-Bold", 8)
        c.drawString(ML + 14, y - 14, "PRIORITY ACTION")
        c.setFillColor(BODY_TEXT)
        c.setFont("Helvetica", 9)
        words = priority_action.split()
        line, cy = "", y - 30
        for w in words:
            test = (line + " " + w).strip()
            if c.stringWidth(test, "Helvetica", 9) <= CW - 28:
                line = test
            else:
                c.drawString(ML + 14, cy, line)
                cy -= 13
                line = w
        if line:
            c.drawString(ML + 14, cy, line)
        y -= pa_h + 16

    if confidence_statement:
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 8)
        words = confidence_statement.split()
        line, cy = "", y
        for w in words:
            test = (line + " " + w).strip()
            if c.stringWidth(test, "Helvetica", 8) <= CW:
                line = test
            else:
                c.drawString(ML, cy, line)
                cy -= 12
                line = w
        if line:
            c.drawString(ML, cy, line)

    _footer(c, 3, report_date)
    c.save()
    return buf.getvalue()
