import type { Slide } from "../../lib/api";
import { ragColor, ragLabel } from "./shared";

export function SlideCover({ slide }: { slide: Slide }) {
  const d = slide.data;
  const rag = d.overall_status || "amber";
  const fund = d.fund_context || {};

  const metaRow = (k: string, v: string, mono = false) => (
    <div style={{ display: "flex", justifyContent: "space-between", gap: 16, padding: "5px 0",
                   borderBottom: "1px solid var(--border)" }}>
      <span style={{ fontSize: 12, color: "var(--text-muted)" }}>{k}</span>
      <span style={{ fontSize: 12, color: "var(--text-primary)", fontWeight: 500,
                      fontFamily: mono ? "var(--font-mono)" : undefined }}>{v}</span>
    </div>
  );

  return (
    <div style={{ display: "flex", height: "100%" }}>
      {/* LEFT navy panel — 40% */}
      <div style={{
        width: "40%", background: "#0F2044", color: "#fff", padding: "clamp(20px,3vw,40px)",
        display: "flex", flexDirection: "column", justifyContent: "space-between",
      }}>
        <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.12em", opacity: 0.8 }}>
          VALUE CREATION COPILOT
        </div>

        <div>
          <div style={{ fontSize: "clamp(22px,3.2vw,34px)", fontWeight: 600, lineHeight: 1.1 }}>
            {d.company_name}
          </div>
          <div style={{ fontSize: 13, color: "#cbd5e1", marginTop: 4 }}>{d.sector}</div>

          <div style={{ height: 1, background: "rgba(255,255,255,0.18)", margin: "18px 0" }} />

          <div style={{ fontSize: 18, fontWeight: 500 }}>{d.report_type_label}</div>
          <div style={{ fontSize: 14, color: "#cbd5e1" }}>{d.period}</div>

          <div style={{ height: 1, background: "rgba(255,255,255,0.18)", margin: "18px 0" }} />

          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
            <span style={{ width: 11, height: 11, borderRadius: "50%", background: ragColor(rag) }} />
            <span style={{ fontSize: 14, fontWeight: 600, textTransform: "uppercase" }}>
              {ragLabel(rag)}
            </span>
            <span style={{ fontSize: 11, color: "#94a3b8" }}>Overall Status</span>
          </div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 13, lineHeight: 1.7 }}>
            <div>IRR Base Case: <span style={{ fontWeight: 600 }}>{d.irr_base ?? "—"}</span></div>
            <div style={{ color: "#cbd5e1" }}>IC Underwritten: {d.irr_ic}</div>
            {d.irr_gap_bps != null && (
              <div style={{ color: d.irr_gap_bps < 0 ? "#fca5a5" : "#86efac" }}>
                Gap: {d.irr_gap_bps > 0 ? "+" : ""}{d.irr_gap_bps}bps
              </div>
            )}
          </div>
        </div>

        <div style={{ fontSize: 10, color: "#64748b" }}>{d.classification}</div>
      </div>

      {/* RIGHT white panel — 60% */}
      <div style={{ flex: 1, padding: "clamp(20px,3vw,40px)", display: "flex",
                     flexDirection: "column", justifyContent: "space-between" }}>
        <div>
          {metaRow("Prepared by", d.prepared_by)}
          {metaRow("Date", d.date)}
          {metaRow("Period", d.period)}
          {metaRow("Classification", d.classification)}
        </div>

        <div>
          <div style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase",
                         letterSpacing: "0.06em", color: "var(--text-muted)", marginBottom: 8 }}>
            Fund Context
          </div>
          {metaRow("Entry EBITDA", `${fund.entry_ebitda ?? "—"} · ${fund.entry_multiple ?? ""}`, true)}
          {metaRow("Initial equity", fund.initial_equity ?? "—", true)}
          {metaRow("Hold target", fund.hold_target ?? "—", true)}
        </div>

        <div style={{ fontSize: 10, color: "var(--text-muted)", lineHeight: 1.6 }}>
          <div>Generated by {d.generated_by}</div>
          <div>
            {d.approved_by
              ? `Approved by ${d.approved_by}${d.approved_at ? ` · ${new Date(d.approved_at).toLocaleString()}` : ""}`
              : "Pending approval"}
          </div>
        </div>
      </div>
    </div>
  );
}
