"""
Demo script: generate a board pack PDF for portco_a_saas from existing data.

Usage:
    uv run python scripts/generate_demo_board_pack.py

Output: data/reports/portco_a_saas_board_pack.pdf

The script loads all real data that has been generated by the monitoring
pipeline and calls the narrative agent + board pack generator.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.agents.alert_synthesis_agent import synthesize, AlertCard
from app.agents.report_narrative_agent import generate, NarrativeOutput
from app.reports.board_pack_generator import generate_board_pack


COMPANY_ID   = "portco_a_saas"
COMPANY_NAME = "Company A — B2B SaaS"
SECTOR       = "B2B SaaS"
PERIOD       = "Q1 2027"

VCP_STORE_PATH    = "data/processed/synthetic_vcp_milestones_seed.json"
KPI_RECORDS_PATH  = "data/processed/portco_a_saas_kpi_records.json"
PEER_BENCH_PATH   = "data/processed/portco_a_saas_peer_benchmark.json"
MONITORING_PATH   = "data/processed/portco_a_saas_vcp_monitoring_graph_state.json"
HITL_PATH         = "data/processed/vcp_confirmation_log.json"
OUTPUT_PATH       = "data/reports/portco_a_saas_board_pack.pdf"


def _load(path: str):
    p = Path(path)
    if not p.exists():
        print(f"[WARN] File not found: {path}")
        return None
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    print(f"[BoardPack Demo] Generating board pack for {COMPANY_NAME}...")

    # ------------------------------------------------------------------
    # Load data
    # ------------------------------------------------------------------
    vcp_all    = _load(VCP_STORE_PATH) or []
    kpi_raw    = _load(KPI_RECORDS_PATH) or []
    peer_bench = _load(PEER_BENCH_PATH)
    monitoring = _load(MONITORING_PATH) or {}
    hitl_raw   = _load(HITL_PATH) or {}

    # Filter milestones for this company
    milestones = [m for m in vcp_all if m.get("company_id") == COMPANY_ID]
    print(f"[BoardPack Demo]  VCP milestones: {len(milestones)}")

    # Extract drift results from monitoring state
    drift_results = monitoring.get("vcp_drift_scores", [])
    if isinstance(drift_results, dict):
        drift_results = drift_results.get("results", [])
    drift_results = [r for r in drift_results if r.get("company_id") == COMPANY_ID]
    print(f"[BoardPack Demo]  Drift results: {len(drift_results)}")

    # KPI records
    if isinstance(kpi_raw, list):
        kpi_records = kpi_raw
    else:
        kpi_records = kpi_raw.get("records", kpi_raw.get("kpi_records", []))
    print(f"[BoardPack Demo]  KPI records: {len(kpi_records)}")

    # HITL decisions — pull from confirmation log entries for this company
    hitl_decisions = []
    if isinstance(hitl_raw, list):
        hitl_decisions = hitl_raw
    elif isinstance(hitl_raw, dict):
        raw_entries = hitl_raw.get("entries", hitl_raw.get("decisions", hitl_raw.get("confirmations", [])))
        hitl_decisions = [
            {
                "decision_type": "VCP Milestone Confirmation",
                "decision": "Approved",
                "timestamp": e.get("logged_at", "")[:19].replace("T", " "),
                "note": e.get("reviewer_note", ""),
            }
            for e in raw_entries
            if e.get("company_id") == COMPANY_ID
        ]

    # Synthetic IRR scenarios for portco_a (based on VCP targets)
    # £20M ARR at deal close → £35.8M ARR target Year 3; EBITDA margin 18%→24%
    irr_scenarios = [
        {
            "scenario": "bear",
            "scenario_description": "p10 EBITDA + 15% multiple compression",
            "exit_annual_ebitda": 6_200_000,
            "exit_multiple": 10.2,
            "exit_enterprise_value": 63_240_000,
            "entry_equity_value": 52_000_000,
            "moic": 1.08,
            "irr": 0.016,
            "irr_percent": 1.6,
            "ic_target_irr": 0.20,
            "irr_gap_vs_ic": -0.184,
            "irr_gap_vs_ic_bps": -1840,
            "ic_target_moic": 2.5,
            "moic_gap_vs_ic": -1.42,
            "scenario_status": "Red",
        },
        {
            "scenario": "base",
            "scenario_description": "p50 EBITDA + current market multiple",
            "exit_annual_ebitda": 8_580_000,
            "exit_multiple": 12.0,
            "exit_enterprise_value": 102_960_000,
            "entry_equity_value": 52_000_000,
            "moic": 1.76,
            "irr": 0.120,
            "irr_percent": 12.0,
            "ic_target_irr": 0.20,
            "irr_gap_vs_ic": -0.080,
            "irr_gap_vs_ic_bps": -800,
            "ic_target_moic": 2.5,
            "moic_gap_vs_ic": -0.74,
            "scenario_status": "Amber",
        },
        {
            "scenario": "bull",
            "scenario_description": "p90 EBITDA + 15% multiple expansion",
            "exit_annual_ebitda": 10_940_000,
            "exit_multiple": 13.8,
            "exit_enterprise_value": 150_972_000,
            "entry_equity_value": 52_000_000,
            "moic": 2.82,
            "irr": 0.231,
            "irr_percent": 23.1,
            "ic_target_irr": 0.20,
            "irr_gap_vs_ic": 0.031,
            "irr_gap_vs_ic_bps": 310,
            "ic_target_moic": 2.5,
            "moic_gap_vs_ic": 0.32,
            "scenario_status": "Green",
        },
    ]

    # ------------------------------------------------------------------
    # Alert & Synthesis Agent
    # ------------------------------------------------------------------
    print("[BoardPack Demo]  Running Alert & Synthesis Agent...")
    alert: AlertCard = synthesize(
        company_id=COMPANY_ID,
        company_name=COMPANY_NAME,
        drift_scores=drift_results,
        kpi_snapshot=None,
        irr_scenarios=irr_scenarios,
        peer_composite=None,
        prefer_llm=True,
    )
    print(f"[BoardPack Demo]  Alert severity: {alert.severity}")
    print(f"[BoardPack Demo]  Headline: {alert.headline}")

    # Derive IRR at risk from base case if the offline agent didn't compute it
    irr_at_risk_bps = alert.irr_at_risk_bps
    if irr_at_risk_bps is None:
        base_sc = next((s for s in irr_scenarios if s.get("scenario") == "base"), None)
        if base_sc and base_sc.get("irr_gap_vs_ic_bps") is not None:
            irr_at_risk_bps = int(base_sc["irr_gap_vs_ic_bps"])

    # ------------------------------------------------------------------
    # Report Narrative Agent
    # ------------------------------------------------------------------
    print("[BoardPack Demo]  Running Report Narrative Agent...")
    narrative: NarrativeOutput = generate(
        company_name=COMPANY_NAME,
        period=PERIOD,
        alert_severity=alert.severity,
        alert_headline=alert.headline,
        alert_root_cause=alert.root_cause,
        alert_recommended_action=alert.recommended_action,
        lever_category=alert.lever_category,
        drift_results=drift_results,
        milestones=milestones,
        peer_benchmark=peer_bench,
        irr_scenarios=irr_scenarios,
        irr_at_risk_bps=alert.irr_at_risk_bps,
        prefer_llm=True,
    )
    print(f"[BoardPack Demo]  Narrative mode: {narrative.narrative_mode}")
    print(f"[BoardPack Demo]  Exec summary: {narrative.exec_summary[:80]}...")

    # ------------------------------------------------------------------
    # Board Pack PDF
    # ------------------------------------------------------------------
    print("[BoardPack Demo]  Assembling board pack PDF...")
    pdf_bytes = generate_board_pack(
        company_name=COMPANY_NAME,
        company_id=COMPANY_ID,
        period=PERIOD,
        sector=SECTOR,
        # Alert
        alert_severity=alert.severity,
        alert_headline=alert.headline,
        alert_root_cause=alert.root_cause,
        alert_recommended_action=alert.recommended_action,
        lever_category=alert.lever_category,
        irr_at_risk_bps=irr_at_risk_bps,
        # Narrative
        exec_summary=narrative.exec_summary,
        key_risks=narrative.key_risks,
        priority_action=narrative.priority_action,
        board_talking_points=narrative.board_talking_points,
        confidence_statement=narrative.confidence_statement,
        narrative_mode=narrative.narrative_mode,
        synthesis_mode=alert.synthesis_mode,
        # Data
        milestones=milestones,
        drift_results=drift_results,
        irr_scenarios=irr_scenarios,
        ic_target_irr=0.20,
        ic_target_moic=2.5,
        entry_equity=52_000_000,
        holding_period=5.0,
        peer_benchmark=peer_bench,
        kpi_records=kpi_records,
        citations=list(alert.citations),
        hitl_decisions=hitl_decisions or None,
        vcp_store_path=VCP_STORE_PATH,
        data_source_path=KPI_RECORDS_PATH,
        output_path=OUTPUT_PATH,
    )

    print(f"\n[BoardPack Demo]  Done. PDF: {OUTPUT_PATH} ({len(pdf_bytes):,} bytes)")
    print(f"[BoardPack Demo]  Pages: 7 (Cover + Exec Summary + VCP Scorecard + "
          f"EBITDA Chart + IRR Scenarios + Peer Benchmarking + Audit Trail)")


if __name__ == "__main__":
    main()
